start_message

2023-08-24 17:12:56,770 - ERROR - data did not save from DB
(psycopg2.errors.NotNullViolation) ОШИБКА:  значение NULL в столбце "number_bk" отношения "stop_work" нарушает ограничение NOT NULL
DETAIL:  Ошибочная строка содержит (1, Воронеж, Энгельса, 3, 2, null, Погодные условия, null, 828093617, null, 2023-08-24 16:37:22, null, null, null).

[SQL: INSERT INTO stop_work (city, object, position, queue, number_bk, cause_stop, cause_info, user_id_stop_work, user_id_continued_work, time_stop_work, time_continued_work, total_time_not_work, note) VALUES (%(city)s, %(object)s, %(position)s, %(queue)s, %(number_bk)s, %(cause_stop)s, %(cause_info)s, %(user_id_stop_work)s, %(user_id_continued_work)s, %(time_stop_work)s, %(time_continued_work)s, %(total_time_not_work)s, %(note)s) RETURNING stop_work.id]
[parameters: {'city': 'Воронеж', 'object': 'Энгельса', 'position': '3', 'queue': '2', 'number_bk': None, 'cause_stop': 'Погодные условия', 'cause_info': None, 'user_id_stop_work': '828093617', 'user_id_continued_work': None, 'time_stop_work': '2023-08-24 16:37:22', 'time_continued_work': None, 'total_time_not_work': None, 'note': None}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
2023-08-24 17:22:01,449 - ERROR - data did not save from DB
(psycopg2.errors.NotNullViolation) ОШИБКА:  значение NULL в столбце "number_bk" отношения "stop_work" нарушает ограничение NOT NULL
DETAIL:  Ошибочная строка содержит (1, Воронеж, Энгельса, 3, 2, null, Поломка крана, null, 828093617, null, 2023-08-24 17:19:49, null, null, null).

[SQL: INSERT INTO stop_work (city, object, position, queue, number_bk, cause_stop, cause_info, user_id_stop_work, user_id_continued_work, time_stop_work, time_continued_work, total_time_not_work, note) VALUES (%(city)s, %(object)s, %(position)s, %(queue)s, %(number_bk)s, %(cause_stop)s, %(cause_info)s, %(user_id_stop_work)s, %(user_id_continued_work)s, %(time_stop_work)s, %(time_continued_work)s, %(total_time_not_work)s, %(note)s) RETURNING stop_work.id]
[parameters: {'city': 'Воронеж', 'object': 'Энгельса', 'position': '3', 'queue': '2', 'number_bk': None, 'cause_stop': 'Поломка крана', 'cause_info': None, 'user_id_stop_work': '828093617', 'user_id_continued_work': None, 'time_stop_work': '2023-08-24 17:19:49', 'time_continued_work': None, 'total_time_not_work': None, 'note': None}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
